# Generated by Django 3.1.5 on 2021-07-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='buat',
            new_name='created',
        ),
    ]
