# Generated by Django 3.1.5 on 2021-07-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210718_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='buat',
        ),
    ]
